plugins:
  - path: ground_truth_slam/
  - path: offline_imu_cam/
  - path: open_vins/
  - path: pose_prediction/
  - path: gldemo/
  - path: timewarp_gl/
  - path: debugview/
  - path: audio_pipeline/
  #- path: frametest/
  # - path: holgoram/
  # - path: zed/
#data: zip+http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip?path=mav0
data: /home/yingj4/Desktop/backup/ILLIXR/data1/
gdb:
  name: native
profile: dbg
