plugins:
  - path: audio_pipeline/
  - path: debugview/
  - path: gldemo/
  - path: ground_truth_slam/
  # - path: holgoram/
  - path: offline_imu_cam/
  - path: open_vins/
  - path: pose_prediction/
  - path: timewarp_gl/
  # - path: zed/
loader:
  name: native
profile: dbg
