plugin_groups:
  - !include "rt_slam_plugins.yaml"
  - !include "core_plugins.yaml"
  - plugin_group:
    - path: gldemo/
    - path: ground_truth_slam/
    - path: debugview/

loader:
  name: tests

data: /does_not_exist
demo_data: /does_not_exist

profile: dbg
