plugins:
  # - path: ground_truth_slam/
  # - path: offline_imu_cam/
  # - path: open_vins/
  # - path: pose_prediction/
  # - path: gldemo/
  # - path: timewarp_gl/
  - path: audio_pipeline/
  # - path: debugview/
  # - path: dummy/
data: ../data1/
loader:
  name: external_tool
  # command: valgrind --error-limit=no --leak-check=full --verbose --log-file=sqlite-leak.txt -- %a
  # command: valgrind --error-limit=no --leak-check=full --track-origins=yes --log-file=sqlite-leak.txt -- %a
  # command: gdb -q --args %a
  command: "%a"
profile: dbg
