plugins:
  - path: ground_truth_slam/
  - path: offline_imu_cam/
  - path: open_vins/
  - path: pose_prediction/
  # - path: gldemo/
  - path: timewarp_gl/
  # - path: debugview/
  - path: audio_pipeline/
  # - path: holgoram/
  # - path: zed/
data: file+zip+http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip?path=mav0
loader:
  name: monado
  monado:
    path: git+https://github.com/ILLIXR/monado_integration.git
    config:
      ILLIXR_PATH: ../../ILLIXR
  openxr_app:
    path: git+https://github.com/ILLIXR/Monado_OpenXR_Simple_Example.git
    config: {}
profile: opt
