plugins:
  - path: ground_truth_slam/
  - path: offline_imu_cam/
  - path: open_vins/
  - path: pose_prediction/
  - path: gldemo/
  - path: timewarp_gl/
  - path: debugview/
  - path: audio_pipeline/
  # - path: hologram/
  # - path: zed/
#data: zip+http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip?path=mav0
data: ../data1/
loader:
  name: native
  # command: valgrind --error-limit=no --leak-check=full --track-origins=yes --log-file=sqlite-leak.txt -- %a
  # command: gdb -q --args %a
  # command: "%a"
profile: opt
