plugin_groups:
  - !include "rt_slam_plugins.yaml"
  - !include "core_plugins.yaml"
  - plugin_group:
      - path: ground_truth_slam/
      - path: debugview/
      - path: gldemo/

data: file+zip+http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip#path=mav0
demo_data: demo_data/
loader:
  name: native
  # command: gdb -q --args %a
profile: opt
