# Run with ground truth pose lookup instead of pose prediction
plugin_groups:
  - !include "core_plugins.yaml"
  - plugin_group:
    - path: pose_lookup/
    - path: gldemo/
    - path: debugview/

data: file+zip+http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip#path=mav0
demo_data: demo_data/
loader:
  name: native
profile: opt
