plugin_group:
  - path: offline_imu_cam/
  # - path: zed/
  - name: OpenVINS
    path:
      git_repo: https://github.com/ILLIXR/open_vins.git
      version: ec8f1e814101f2ed2692f1d3d3f1f5272ed1a484
  - path: imu_integrator/
  - path: pose_prediction/
